### ISSUE TITLE
`/usr/bin/env: ‘lua’: No such file or directory` in the koappimage docker image

### ISSUE THREAD

**Issue by Toromtomtom** [koreader/virdevenv#58]
When following the [instructions for setting up a virtual dev environment](https://github.com/koreader/virdevenv/blob/master/README.md), `kodev test` in the resulting Ubuntu system fails with `/usr/bin/env: ‘lua’: No such file or directory`. After `sudo apt update && sudo apt install lua5.1`, tests can be run. So I guess `lua5.1` should be added to the packages installed in the image somewhere.

**Comment by Frenzie** [comment]
That's caused by this line:
https://github.com/koreader/virdevenv/blob/e0293b5e133c6934e6db8d4c4d250fe788049c0d/docker/ubuntu/baseimage/install_luarocks.sh#L20

However, removing that line would break `make testfront`.

> tests can be run.

Without failing en masse? That is, it passes it on to LuaJIT? Might as well in that case, I suppose. Or maybe rewrite either make test or kodev test a little.

**Comment by Toromtomtom** [comment]
> Without failing en masse?

Yes. I get one failure in base in  `/spec/base/unit/koptcontext_spec.lua:154`, everything else passes.

Although the other tests in `koptcontext_spec.lua` pass, they all write `error: Unable to read ICC workflow` to the console. [That seems to happen in CI as well, though](https://app.circleci.com/pipelines/github/koreader/koreader-base/921/workflows/fbb45e1e-a308-4f41-aa50-11964021c923/jobs/8332/parallel-runs/0/steps/0-105).
